services:
  server:
    build:
      context: .
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    ports:
      - 4000:4000
